// Code generated by a template
using PclSharp.Struct;

namespace PclSharp.Features
{
	public abstract class FPFHEstimation<PointT, PointNT> : FeatureFromNormals<PointT, PointNT, FPFHSignature33>
	{
		public abstract (int f1, int f2, int f3) NrSubdivisions { get; set; }
	}
}
