// Code generated by a template
using PclSharp.Common;
using PclSharp.Search;
using PclSharp.Std;

namespace PclSharp.Segmentation
{
	public abstract class EuclideanClusterExtraction<PointT> : PclBase<PointT>
	{
		public abstract void SetSearchMethod(Search<PointT> search);
		public abstract void Extract(Vector<PointIndices> clusters);
	}
}
