// Code generated by a template
using PclSharp.Common;
using PclSharp.Search;
using PclSharp.Std;

namespace PclSharp.Segmentation
{
	public abstract class SupervoxelClusters<PointT> : UnmanagedObject
	{
		public abstract int Count { get; }
	}
}
