// Code generated by a template
using System;
using PclSharp.Common;
using PclSharp.Search;
using PclSharp.Std;
using PclSharp.Struct;

namespace PclSharp.Segmentation
{
	public abstract class Supervoxel<PointT> : UnmanagedObject
	{
		public abstract Normal Normal { get; set; }
		public abstract PointXYZRGBA Centroid { get; set; }
		public abstract IntPtr Voxels { get; }
		public abstract IntPtr Normals { get; }
	}
}
