// Code generated by a template
#pragma once
#include "..\export.h"
#include <vector>
#include "pcl\point_types.h"


using namespace std;
using namespace pcl;


typedef vector<PointXYZ> vectorType;

#ifdef __cplusplus  
extern "C" {  
#endif

EXPORT(vectorType*) std_vector_xyz_ctor()
{
	return new vector<PointXYZ>();
}

EXPORT(vectorType*) std_vector_xyz_ctor_count(int count)
{
	return new vector<PointXYZ>(count);
}

EXPORT(void) std_vector_xyz_delete(vector<PointXYZ>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) std_vector_xyz_at(vector<PointXYZ>* ptr, size_t idx, PointXYZ* value)
{
	*value = ptr->at(idx);
}

EXPORT(size_t) std_vector_xyz_size(vector<PointXYZ>* ptr)
{
	return ptr->size();
}

EXPORT(void) std_vector_xyz_clear(vector<PointXYZ>* ptr)
{
	ptr->clear();
}

EXPORT(void) std_vector_xyz_resize(vector<PointXYZ>* ptr, int32_t size)
{
	ptr->resize(size);
}

EXPORT(void) std_vector_xyz_add(vector<PointXYZ>* ptr, PointXYZ value)
{
	//the value needs to be aligned to be pushed into the cloud, so do that.
	PointXYZ deref;
	memcpy(&deref, &value, sizeof(PointXYZ));
	ptr->push_back(deref);
}

EXPORT(void) std_vector_xyz_insert(vector<PointXYZ>* ptr, ptrdiff_t index, PointXYZ value)
{
	//the value needs to be aligned to be pushed into the cloud, so do that.
	PointXYZ deref;
	memcpy(&deref, &value, sizeof(PointXYZ));
	ptr->insert(ptr->begin()+index, deref);
}

EXPORT(PointXYZ*) std_vector_xyz_data(vector<PointXYZ>* ptr)
{
	return ptr->data();
}

#ifdef __cplusplus  
}
#endif
