// Code generated by a template
#pragma once
#include "..\export.h"
#include <vector>
#include "pcl\point_types.h"


using namespace std;
using namespace pcl;


typedef vector<Normal> vectorType;

#ifdef __cplusplus  
extern "C" {  
#endif

EXPORT(vectorType*) std_vector_normal_ctor()
{
	return new vector<Normal>();
}

EXPORT(vectorType*) std_vector_normal_ctor_count(int count)
{
	return new vector<Normal>(count);
}

EXPORT(void) std_vector_normal_delete(vector<Normal>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) std_vector_normal_at(vector<Normal>* ptr, size_t idx, Normal* value)
{
	*value = ptr->at(idx);
}

EXPORT(size_t) std_vector_normal_size(vector<Normal>* ptr)
{
	return ptr->size();
}

EXPORT(void) std_vector_normal_clear(vector<Normal>* ptr)
{
	ptr->clear();
}

EXPORT(void) std_vector_normal_resize(vector<Normal>* ptr, int32_t size)
{
	ptr->resize(size);
}

EXPORT(void) std_vector_normal_add(vector<Normal>* ptr, Normal value)
{
	//the value needs to be aligned to be pushed into the cloud, so do that.
	Normal deref;
	memcpy(&deref, &value, sizeof(Normal));
	ptr->push_back(deref);
}

EXPORT(void) std_vector_normal_insert(vector<Normal>* ptr, ptrdiff_t index, Normal value)
{
	//the value needs to be aligned to be pushed into the cloud, so do that.
	Normal deref;
	memcpy(&deref, &value, sizeof(Normal));
	ptr->insert(ptr->begin()+index, deref);
}

EXPORT(Normal*) std_vector_normal_data(vector<Normal>* ptr)
{
	return ptr->data();
}

#ifdef __cplusplus  
}
#endif
