// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PclSharp.Std;
namespace PclSharp.Common
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr modelcoefficients_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void modelcoefficients_delete(ref IntPtr ptr);

		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr modelcoefficients_values(IntPtr ptr);
	}

	public class ModelCoefficients : UnmanagedObject
	{
		public Vector<float> Values { get; }

		public ModelCoefficients()
		{
			_ptr = Invoke.modelcoefficients_ctor();

			Values = new VectorOfFloat(Invoke.modelcoefficients_values(_ptr));
		}

		protected override void DisposeObject()
		{
			Invoke.modelcoefficients_delete(ref _ptr);
		}
	}
}
