// Code generated by a template
using PclSharp.Common;
using PclSharp.Search;
using PclSharp.Std;
using PclSharp.Struct;
using System.Numerics;

namespace PclSharp.Common
{
	public class PCA
	{
		public enum Flag
		{
			Increase,
			Preserve
		}
	}

	public abstract class PCA<PointT> : PclBase<PointT>
	{
		public abstract Vector4 Mean { get; }
		public abstract Vector3 EigenValues { get; }

		public abstract void Update(PointT input, PCA.Flag flag = PCA.Flag.Preserve);
	}
}
