// Code generated by a template
using System;
using System.Collections;
using System.Collections.Generic;

namespace PclSharp.Std
{
	public abstract class MultiMap<TKey, TValue> : UnmanagedObject, IEnumerable<KeyValuePair<TKey, TValue>>
	{
		protected bool _suppressDispose;

		public abstract IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator()
			=> GetEnumerator();
	}
}
