// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Numerics;
using PclSharp.Struct;


namespace PclSharp.Std
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_xyz_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_xyz_ctor_count(int count);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_delete(ref IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_at(IntPtr ptr,  UIntPtr idx, ref PointXYZ value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern UIntPtr std_vector_xyz_size(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_clear(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_resize(IntPtr ptr, int size);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_add(IntPtr ptr, PointXYZ value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_xyz_data(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_xyz_insert(IntPtr ptr, IntPtr idx, PointXYZ value);
	}

	public unsafe class VectorOfXYZ : Vector<PointXYZ>
	{	
		private bool _suppressDispose;

		public override int Count => (int)Invoke.std_vector_xyz_size(_ptr);
		public IntPtr Data => Invoke.std_vector_xyz_data(_ptr);
		public PointXYZ* DataU => (PointXYZ*)Data;

		public VectorOfXYZ()
		{
			_ptr = Invoke.std_vector_xyz_ctor();
		}

		public VectorOfXYZ(int count)
		{
			_ptr = Invoke.std_vector_xyz_ctor_count(count);
		}

		/// <summary>
        /// construct as a copy of the list
        /// </summary>
        /// <param name="list"></param>
		public VectorOfXYZ(List<PointXYZ> list)
        {
            var arr = list.ToArray();
            _ptr = Invoke.std_vector_xyz_ctor_count(arr.Length);
            
            var dptr = (PointXYZ*)Data;
            for(var i = 0; i < arr.Length; i++)
                dptr[i] = arr[i];
        }

		internal VectorOfXYZ(IntPtr ptr)
		{
			_suppressDispose = true;
			_ptr = ptr;
		}

		public override void At(int idx, ref PointXYZ value)
		{
			Invoke.std_vector_xyz_at(_ptr, (UIntPtr)idx, ref value);
		}

		public override PointXYZ this[int idx]
        {
            get { return DataU[idx]; }
			set { DataU[idx] = value; }
		}

		public override void Resize(int size)
			=> Invoke.std_vector_xyz_resize(_ptr, size);

		public override void Add(PointXYZ value)
			=> Invoke.std_vector_xyz_add(_ptr, value);

		public override void CopyTo(PointXYZ[] arr, int idx)
		{
            fixed (PointXYZ* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(PointXYZ) * Count));
            }
		}

		public override PointXYZ[] ToArray()
		{
			var arr = new PointXYZ[Count];
            fixed (PointXYZ* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(PointXYZ) * arr.Length));
            }

			return arr;
		}

		public override void Clear() => Invoke.std_vector_xyz_clear(_ptr);

		public override void Insert(int index, PointXYZ item)
			=> Invoke.std_vector_xyz_insert(_ptr, (IntPtr)index, item);

		public override IEnumerator<PointXYZ> GetEnumerator()
		{
			var count = Count;
			for(var i = 0; i < count; i++)
				yield return this[i];
		}

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;
			Invoke.std_vector_xyz_delete(ref _ptr);
		}
	}
}
