// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Numerics;
using PclSharp.Struct;


namespace PclSharp.Std
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_normal_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_normal_ctor_count(int count);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_delete(ref IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_at(IntPtr ptr,  UIntPtr idx, ref Normal value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern UIntPtr std_vector_normal_size(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_clear(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_resize(IntPtr ptr, int size);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_add(IntPtr ptr, Normal value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_normal_data(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_normal_insert(IntPtr ptr, IntPtr idx, Normal value);
	}

	public unsafe class VectorOfNormal : Vector<Normal>
	{	
		private bool _suppressDispose;

		public override int Count => (int)Invoke.std_vector_normal_size(_ptr);
		public IntPtr Data => Invoke.std_vector_normal_data(_ptr);
		public Normal* DataU => (Normal*)Data;

		public VectorOfNormal()
		{
			_ptr = Invoke.std_vector_normal_ctor();
		}

		public VectorOfNormal(int count)
		{
			_ptr = Invoke.std_vector_normal_ctor_count(count);
		}

		/// <summary>
        /// construct as a copy of the list
        /// </summary>
        /// <param name="list"></param>
		public VectorOfNormal(List<Normal> list)
        {
            var arr = list.ToArray();
            _ptr = Invoke.std_vector_normal_ctor_count(arr.Length);
            
            var dptr = (Normal*)Data;
            for(var i = 0; i < arr.Length; i++)
                dptr[i] = arr[i];
        }

		internal VectorOfNormal(IntPtr ptr)
		{
			_suppressDispose = true;
			_ptr = ptr;
		}

		public override void At(int idx, ref Normal value)
		{
			Invoke.std_vector_normal_at(_ptr, (UIntPtr)idx, ref value);
		}

		public override Normal this[int idx]
        {
            get { return DataU[idx]; }
			set { DataU[idx] = value; }
		}

		public override void Resize(int size)
			=> Invoke.std_vector_normal_resize(_ptr, size);

		public override void Add(Normal value)
			=> Invoke.std_vector_normal_add(_ptr, value);

		public override void CopyTo(Normal[] arr, int idx)
		{
            fixed (Normal* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(Normal) * Count));
            }
		}

		public override Normal[] ToArray()
		{
			var arr = new Normal[Count];
            fixed (Normal* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(Normal) * arr.Length));
            }

			return arr;
		}

		public override void Clear() => Invoke.std_vector_normal_clear(_ptr);

		public override void Insert(int index, Normal item)
			=> Invoke.std_vector_normal_insert(_ptr, (IntPtr)index, item);

		public override IEnumerator<Normal> GetEnumerator()
		{
			var count = Count;
			for(var i = 0; i < count; i++)
				yield return this[i];
		}

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;
			Invoke.std_vector_normal_delete(ref _ptr);
		}
	}
}
