// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;


namespace PclSharp.Std
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_float_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_float_ctor_count(int count);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_delete(ref IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_at(IntPtr ptr,  UIntPtr idx, ref float value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern UIntPtr std_vector_float_size(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_clear(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_resize(IntPtr ptr, int size);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_add(IntPtr ptr, float value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr std_vector_float_data(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void std_vector_float_insert(IntPtr ptr, IntPtr idx, float value);
	}

	public unsafe class VectorOfFloat : Vector<float>
	{	
		private bool _suppressDispose;

		public override int Count => (int)Invoke.std_vector_float_size(_ptr);
		public IntPtr Data => Invoke.std_vector_float_data(_ptr);
		public float* DataU => (float*)Data;

		public VectorOfFloat()
		{
			_ptr = Invoke.std_vector_float_ctor();
		}

		public VectorOfFloat(int count)
		{
			_ptr = Invoke.std_vector_float_ctor_count(count);
		}

		/// <summary>
        /// construct as a copy of the list
        /// </summary>
        /// <param name="list"></param>
		public VectorOfFloat(List<float> list)
        {
            var arr = list.ToArray();
            _ptr = Invoke.std_vector_float_ctor_count(arr.Length);
            
            var dptr = (float*)Data;
            for(var i = 0; i < arr.Length; i++)
                dptr[i] = arr[i];
        }

		internal VectorOfFloat(IntPtr ptr)
		{
			_suppressDispose = true;
			_ptr = ptr;
		}

		public override void At(int idx, ref float value)
		{
			Invoke.std_vector_float_at(_ptr, (UIntPtr)idx, ref value);
		}

		public override float this[int idx]
        {
            get { return DataU[idx]; }
			set { DataU[idx] = value; }
		}

		public override void Resize(int size)
			=> Invoke.std_vector_float_resize(_ptr, size);

		public override void Add(float value)
			=> Invoke.std_vector_float_add(_ptr, value);

		public override void CopyTo(float[] arr, int idx)
		{
            fixed (float* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(float) * Count));
            }
		}

		public override float[] ToArray()
		{
			var arr = new float[Count];
            fixed (float* aptr = arr)
            {
                Unsafe.CopyBlockUnaligned(aptr, DataU, (uint)(sizeof(float) * arr.Length));
            }

			return arr;
		}

		public override void Clear() => Invoke.std_vector_float_clear(_ptr);

		public override void Insert(int index, float item)
			=> Invoke.std_vector_float_insert(_ptr, (IntPtr)index, item);

		public override IEnumerator<float> GetEnumerator()
		{
			var count = Count;
			for(var i = 0; i < count; i++)
				yield return this[i];
		}

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;
			Invoke.std_vector_float_delete(ref _ptr);
		}
	}
}
