// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
namespace PclSharp.IO
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr io_pcdreader_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void io_pcdreader_delete(ref IntPtr ptr);

		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern int io_pcdreader_read_xyz(IntPtr ptr, string fileName, IntPtr cloud, int offset);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern int io_pcdreader_read_xyzrgba(IntPtr ptr, string fileName, IntPtr cloud, int offset);
	}

	public class PCDReader : UnmanagedObject
	{
		public PCDReader()
		{
			_ptr = Invoke.io_pcdreader_ctor();
		}

		public int Read(string fileName, PointCloud<PointXYZ> cloud, int offset=0)
		{
			var res = Invoke.io_pcdreader_read_xyz(_ptr, fileName, cloud.Ptr, offset);
			return res;
		}

		public int Read(string fileName, PointCloud<PointXYZRGBA> cloud, int offset=0)
		{
			return Invoke.io_pcdreader_read_xyzrgba(_ptr, fileName, cloud, offset);
		}

		protected override void DisposeObject()
		{
			Invoke.io_pcdreader_delete(ref _ptr);
		}
	}
}
