// Code generated by a template
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using PclSharp.Struct;
using PclSharp.Std;

namespace PclSharp
{
	public static unsafe partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pclbase_xyzrgba_setInputCloud(IntPtr ptr, IntPtr cloud);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pclbase_xyzrgba_setIndices(IntPtr ptr, IntPtr indices);
		
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern PointXYZRGBA* pclbase_xyzrgba_indexGet(IntPtr ptr, int idx);
	}

	public static unsafe class PclBaseOfXYZRGBA
	{
		public static void SetInputCloud(this PclBase<PointXYZRGBA> _ptr, PointCloud<PointXYZRGBA> cloud)
			=> Invoke.pclbase_xyzrgba_setInputCloud(_ptr, cloud);

		public static void SetIndices(this PclBase<PointXYZRGBA> _ptr, VectorOfInt indices)
			=> Invoke.pclbase_xyzrgba_setIndices(_ptr, indices);

		public static ref PointXYZRGBA Index(this PclBase<PointXYZRGBA> _ptr, int idx)
			=> ref Unsafe.AsRef<PointXYZRGBA>(Invoke.pclbase_xyzrgba_indexGet(_ptr, idx));
	}
}
