// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Std;
namespace PclSharp
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointindices_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointindices_delete(ref IntPtr ptr);

		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointindices_indices(IntPtr ptr);
	}

	public class PointIndices : UnmanagedObject
	{
		private VectorOfInt _indices;
		public VectorOfInt Indices { get; }

		public PointIndices()
		{
			_ptr = Invoke.pointindices_ctor();

			_indices = new VectorOfInt(Invoke.pointindices_indices(_ptr));
		}

		protected override void DisposeObject()
		{
			Invoke.pointindices_delete(ref _ptr);
		}
	}
}
