// Code generated by a template
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.InteropServices;
using PclSharp.Std;
namespace PclSharp
{
	public static partial class Invoke
	{
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointindices_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointindices_delete(ref IntPtr ptr);

		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointindices_indices(IntPtr ptr);
	}

	public class PointIndices : UnmanagedObject
	{
		private bool _suppressDispose;

		public VectorOfInt Indices { get; }

		public PointIndices()
		{
			_ptr = Invoke.pointindices_ctor();
			Indices = new VectorOfInt(Invoke.pointindices_indices(_ptr));
		}

		internal PointIndices(IntPtr ptr)
		{
			_ptr = ptr;
			Indices = new VectorOfInt(Invoke.pointindices_indices(_ptr));

			_suppressDispose = true;
		}

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;

			Invoke.pointindices_delete(ref _ptr);
		}
	}
}
