// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
using System.Runtime.CompilerServices;

namespace PclSharp
{
	public static partial class Invoke
	{
		//ctor/dctor
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_normal_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_normal_ctor_indices(IntPtr cloud, IntPtr indices);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_normal_ctor_wh(uint width, uint height);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_delete(ref IntPtr ptr);
		//methods
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern unsafe Normal* pointcloud_normal_at_colrow(IntPtr ptr, int col, int row);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_clear(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern unsafe void pointcloud_normal_add(IntPtr ptr, Normal* value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_downsample(IntPtr ptr, int factor, IntPtr output);
		//properties
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern UIntPtr pointcloud_normal_size(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_normal_data(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern uint pointcloud_normal_width(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_width_set(IntPtr ptr, uint width);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern uint pointcloud_normal_height(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_height_set(IntPtr ptr, uint height);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_normal_points(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_normal_setIsDense(IntPtr ptr, bool value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern bool pointcloud_normal_getIsDense(IntPtr ptr);
		[return: MarshalAs(UnmanagedType.Bool)]
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern bool pointcloud_normal_isOrganized(IntPtr ptr);
	}

	public unsafe class PointCloudOfNormal : PointCloud<Normal>
	{
		private bool _suppressDispose;

		public override int Width 
		{
			get { return (int)Invoke.pointcloud_normal_width(_ptr); }
			set { Invoke.pointcloud_normal_width_set(_ptr, (uint)value); }
		}
		public override int Height 
		{
			get { return (int)Invoke.pointcloud_normal_height(_ptr); }
			set { Invoke.pointcloud_normal_height_set(_ptr, (uint)value); }
		}
		public override bool IsDense
		{
			get { return Invoke.pointcloud_normal_getIsDense(_ptr); }
            set { Invoke.pointcloud_normal_setIsDense(_ptr, value); }
		}
		public override int Count => (int)Invoke.pointcloud_normal_size(_ptr);
		public int Size => Count;
		public override bool IsOrganized => Invoke.pointcloud_normal_isOrganized(_ptr);
		public Normal* Data => (Normal*)Invoke.pointcloud_normal_data(_ptr);

		private VectorOfNormal _points;
		public override Vector<Normal> Points => _points;

		private PointCloudOfNormal(IntPtr ptr)
		{
			_ptr = ptr;
			_points = new VectorOfNormal(Invoke.pointcloud_normal_points(_ptr));
		}

		internal PointCloudOfNormal(IntPtr ptr, bool suppressDispose)
			:this(ptr)
		{
			_suppressDispose = suppressDispose;
		}

		public PointCloudOfNormal() 
			: this(Invoke.pointcloud_normal_ctor())
		{
		}

		public PointCloudOfNormal(int width, int height)
			: this(Invoke.pointcloud_normal_ctor_wh((uint)width, (uint)height))
		{
		}

		public PointCloudOfNormal(PointCloudOfNormal cloud, Std.VectorOfInt indices)
			:this (Invoke.pointcloud_normal_ctor_indices(cloud.Ptr, indices.Ptr))
		{
		}

		public void Downsample(int factor, PointCloud<Normal> output)
			=> Invoke.pointcloud_normal_downsample(_ptr, factor, output);

		public override ref Normal At(int col, int row)
			=>  ref Unsafe.AsRef<Normal>(Invoke.pointcloud_normal_at_colrow(_ptr, col, row));

		public override void Add(Normal value)
			=> Invoke.pointcloud_normal_add(_ptr, &value);

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;
			Invoke.pointcloud_normal_delete(ref _ptr);
		}
	}
}
