// Code generated by a template
#pragma once
#include "..\export.h"
#include <pcl/ModelCoefficients.h>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif

EXPORT(ModelCoefficients*) modelcoefficients_ctor()
{
	return new ModelCoefficients();
}

EXPORT(void) modelcoefficients_delete(ModelCoefficients** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(vector<float>*) modelcoefficients_values(ModelCoefficients* ptr)
{
	return &ptr->values;
}

#ifdef __cplusplus  
}
#endif
