// Code generated by a template
#pragma once
#include "..\export.h"
#include <pcl/io/pcd_io.h>

using namespace pcl;
using namespace std;

#ifdef __cplusplus
extern "C" {
#endif

EXPORT(PCDReader*) io_pcdreader_ctor()
{
	return new PCDReader();
}

EXPORT(void) io_pcdreader_delete(PCDReader** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(int32_t) io_pcdreader_read_xyz(PCDReader* ptr, const char* str, PointCloud<PointXYZ>* cloud, int offset)
{
	return ptr->read(string(str), *cloud, offset);
}
EXPORT(int32_t) io_pcdreader_read_xyzrgba(PCDReader* ptr, const char* str, PointCloud<PointXYZRGBA>* cloud, int offset)
{ return ptr->read(string(str), *cloud, offset); }


#ifdef __cplusplus  
}
#endif
