// Code generated by a template
#pragma once
#include "..\export.h"
#include <Eigen/Core>

using namespace Eigen;

typedef Eigen::Matrix<float, 4, 4> 	Matrix4f;

#ifdef __cplusplus
extern "C" {
#endif

EXPORT(Matrix4f*) eigen_matrix4_f_ctor()
{ return new Matrix4f(); }

EXPORT(void) eigen_matrix4_f_delete(Matrix4f** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) eigen_matrix4_f_setIndex(Matrix4f* ptr, int row, int col, float value)
{ ptr->operator()(row, col) = value; }
EXPORT(float) eigen_matrix4_f_getIndex(Matrix4f* ptr, int row, int col)
{ return ptr->operator()(row, col); }

EXPORT(float*) eigen_matrix4_f_data(Matrix4f* ptr)
{ return ptr->data(); }

#ifdef __cplusplus  
}
#endif
