// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\point_types.h"
#include <pcl/segmentation/supervoxel_clustering.h>

using namespace pcl;
using namespace std;

typedef boost::shared_ptr<PointCloud<PointXYZRGBA>> boost_cloud;
typedef boost::shared_ptr<PointCloud<Normal>> normal_cloud;
typedef boost::shared_ptr<vector<int>> boost_indices;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(SupervoxelClustering<PointXYZRGBA>*) segmentation_supervoxelclustering_xyzrgba_ctor(float voxelResolution, float seedResolution)
{
	return new SupervoxelClustering<PointXYZRGBA>(voxelResolution, seedResolution);
}

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_delete(SupervoxelClustering<PointXYZRGBA>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setInputCloud(SupervoxelClustering<PointXYZRGBA>* ptr, PointCloud<PointXYZRGBA>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setIndices(SupervoxelClustering<PointXYZRGBA>* ptr, std::vector<int>* indices)
{ ptr->setIndices(boost_indices(boost_indices(), indices)); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setNormalCloud(SupervoxelClustering<PointXYZRGBA>* ptr, PointCloud<Normal>* cloud)
{
	ptr->setNormalCloud(normal_cloud(normal_cloud(), cloud));
}

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_extract(SupervoxelClustering<PointXYZRGBA>* ptr, map<uint32_t, Supervoxel<PointXYZRGBA>::Ptr>* clusters)
{
	ptr->extract(*clusters);
}

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_refineSupervoxels(SupervoxelClustering<PointXYZRGBA>* ptr, int iterations, map<uint32_t, Supervoxel<PointXYZRGBA>::Ptr>* clusters)
{ ptr->refineSupervoxels(iterations, *clusters); }

EXPORT(PointCloud<PointXYZL>*) segmentation_supervoxelclustering_xyzrgba_getLabeledCloud(SupervoxelClustering<PointXYZRGBA>* ptr)
{ return ptr->getLabeledCloud().get(); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_getSupervoxelAdjacency(SupervoxelClustering<PointXYZRGBA>* ptr, std::multimap< uint32_t, uint32_t >* multimap)
{ ptr->getSupervoxelAdjacency(*multimap); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setColorImportance(SupervoxelClustering<PointXYZRGBA>* ptr, float value)
{ ptr->setColorImportance(value); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setNormalImportance(SupervoxelClustering<PointXYZRGBA>* ptr, float value)
{ ptr->setNormalImportance(value); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setSpatialImportance(SupervoxelClustering<PointXYZRGBA>* ptr, float value)
{ ptr->setSpatialImportance(value); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setUseSingleCameraTransform(SupervoxelClustering<PointXYZRGBA>* ptr, int value)
{ ptr->setUseSingleCameraTransform(value); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setVoxelResolution(SupervoxelClustering<PointXYZRGBA>* ptr, float value)
{ ptr->setVoxelResolution(value); }
EXPORT(float) segmentation_supervoxelclustering_xyzrgba_getVoxelResolution(SupervoxelClustering<PointXYZRGBA>* ptr)
{ return ptr->getVoxelResolution(); }

EXPORT(void) segmentation_supervoxelclustering_xyzrgba_setSeedResolution(SupervoxelClustering<PointXYZRGBA>* ptr, float value)
{ ptr->setSeedResolution(value); }
EXPORT(float) segmentation_supervoxelclustering_xyzrgba_getSeedResolution(SupervoxelClustering<PointXYZRGBA>* ptr)
{ return ptr->getSeedResolution(); }

#ifdef __cplusplus  
}
#endif  
