// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\point_types.h"
#include <pcl/segmentation/supervoxel_clustering.h>

using namespace pcl;
using namespace std;

typedef boost::shared_ptr<PointCloud<PointXYZ>> boost_cloud;
typedef map<uint32_t, Supervoxel<PointXYZ>::Ptr> SupervoxelClusters;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(SupervoxelClusters*) segmentation_supervoxelclusters_xyz_ctor()
{
	return new SupervoxelClusters();
}

EXPORT(void) segmentation_supervoxelclusters_xyz_delete(map<uint32_t, Supervoxel<PointXYZ>::Ptr>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(Supervoxel<PointXYZ>*) segmentation_supervoxelclusters_xyz_at(map<uint32_t, Supervoxel<PointXYZ>::Ptr>* ptr, uint32_t key)
{ return ptr->at(key).get(); }

EXPORT(int) segmentation_supervoxelclusters_xyz_count(map<uint32_t, Supervoxel<PointXYZ>::Ptr>* ptr)
{ return ptr->size(); }

#ifdef __cplusplus  
}
#endif  
