// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\point_types.h"
#include <pcl/segmentation/supervoxel_clustering.h>

using namespace pcl;
using namespace std;

typedef boost::shared_ptr<PointCloud<PointXYZRGBA>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(Supervoxel<PointXYZRGBA>*) segmentation_supervoxel_xyzrgba_ctor()
{
	return new Supervoxel<PointXYZRGBA>();
}

EXPORT(void) segmentation_supervoxel_xyzrgba_delete(Supervoxel<PointXYZRGBA>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) segmentation_supervoxel_xyzrgba_setNormal(Supervoxel<PointXYZRGBA>* ptr, Normal* value)
{ 
	//the value needs to be aligned to be pushed into the cloud, so do that.
	Normal deref;
	memcpy(&deref, value, sizeof(Normal));
	ptr->normal_ = deref; 
}
EXPORT(Normal*) segmentation_supervoxel_xyzrgba_getNormal(Supervoxel<PointXYZRGBA>* ptr)
{ return &ptr->normal_; }

EXPORT(PointXYZRGBA*) segmentation_supervoxel_xyzrgba_getCentroid(Supervoxel<PointXYZRGBA>* ptr)
{ return &ptr->centroid_; }
EXPORT(void) segmentation_supervoxel_xyzrgba_setCentroid(Supervoxel<PointXYZRGBA>* ptr, PointXYZRGBA* value)
{ 
	//the value needs to be aligned to be pushed into the cloud, so do that.
	PointXYZRGBA deref;
	memcpy(&deref, value, sizeof(PointXYZRGBA));
	ptr->centroid_ = deref; 
}

EXPORT(PointCloud<PointXYZRGBA>*) segmentation_supervoxel_xyzrgba_getVoxels(Supervoxel<PointXYZRGBA>* ptr)
{ return ptr->voxels_.get(); }

EXPORT(PointCloud<Normal>*) segmentation_supervoxel_xyzrgba_getNormals(Supervoxel<PointXYZRGBA>* ptr)
{ return ptr->normals_.get(); }

#ifdef __cplusplus  
}
#endif  
