// Code generated by a template
namespace PclSharp.Filters
{
	public abstract class Heightmap2D<PointT> : Filter<PointT>
	{
		public abstract float BinSize { get; set; }
		public abstract float MinDistBetweenMaxima { get; set; }
		public abstract int MaximaNumberAfterFiltering { get; }
		public abstract Std.VectorOfInt MaximaCloudIndicesFiltered { get; }

		public abstract void SetGroundCoeffs(Eigen.VectorXf coeffs);
	}
}
