// Code generated by a template
namespace PclSharp.Filters
{
	public abstract class StatisticalOutlierRemoval<PointT> : FilterIndices<PointT>
	{
		public abstract int MeanK { get; set; }
		public abstract double StdDevMulThresh { get; set; }
	}
}
