// Code generated by a template
namespace PclSharp.Filters
{
	public abstract class VoxelGrid<PointT> : Filter<PointT>
	{
		public abstract (double min, double max) FilterLimits { get; set; }
		public abstract string FilterFieldName { get; set; }
	}
}
