// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/statistical_outlier_removal.h>

using namespace pcl;
using namespace std;

typedef StatisticalOutlierRemoval<PointXYZ> filter_t;
typedef boost::shared_ptr<PointCloud<PointXYZ>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(filter_t*) filters_statisticalOutlierRemoval_xyz_ctor(bool extractRemovedIndices)
{
	return new filter_t(extractRemovedIndices);
}

EXPORT(void) filters_statisticalOutlierRemoval_xyz_delete(filter_t** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_statisticalOutlierRemoval_xyz_filter(StatisticalOutlierRemoval<PointXYZ>* ptr, PointCloud<PointXYZ>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setInputCloud(StatisticalOutlierRemoval<PointXYZ>* ptr, PointCloud<PointXYZ>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setIndices(StatisticalOutlierRemoval<PointXYZ>* ptr, vector<int>* indices)
{
	ptr->setIndices(boost::shared_ptr<vector<int>>(boost::shared_ptr<vector<int>>(), indices));
}

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setMeanK(StatisticalOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setMeanK(value); }
EXPORT(int) filters_statisticalOutlierRemoval_xyz_getMeanK(StatisticalOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getMeanK(); }

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setStddevMulThresh(StatisticalOutlierRemoval<PointXYZ>* ptr, double value)
{ ptr->setStddevMulThresh(value); }
EXPORT(double) filters_statisticalOutlierRemoval_xyz_getStddevMulThresh(StatisticalOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getStddevMulThresh(); }

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setKeepOrganized(StatisticalOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setKeepOrganized(value); }
EXPORT(int) filters_statisticalOutlierRemoval_xyz_getKeepOrganized(StatisticalOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getKeepOrganized(); }

EXPORT(void) filters_statisticalOutlierRemoval_xyz_setNegative(StatisticalOutlierRemoval<PointXYZ>* ptr, int value)
{ ptr->setNegative(value); }
EXPORT(int) filters_statisticalOutlierRemoval_xyz_getNegative(StatisticalOutlierRemoval<PointXYZ>* ptr)
{ return ptr->getNegative(); }

#ifdef __cplusplus  
}
#endif  
