// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"

using namespace pcl;
using namespace std;

typedef vector<PointXYZL, Eigen::aligned_allocator<PointXYZL>> point_vector;

#ifdef __cplusplus  
extern "C" {  // only need to export C interface if  
			  // used by C++ source code  
#endif  

EXPORT(PointCloud<PointXYZL>*) pointcloud_xyzl_ctor()
{
	return new PointCloud<PointXYZL>();
}

EXPORT(PointCloud<PointXYZL>*) pointcloud_xyzl_ctor_wh(uint32_t width, uint32_t height)
{
	return new PointCloud<PointXYZL>(width, height);
}

EXPORT(PointCloud<PointXYZL>*) pointcloud_xyzl_ctor_indices(PointCloud<PointXYZL>* cloud, vector<int>* indices)
{
	if (indices == NULL)
		return new PointCloud<PointXYZL>(*cloud);
	else
		return new PointCloud<PointXYZL>(*cloud, *indices);
}

EXPORT(void) pointcloud_xyzl_delete(PointCloud<PointXYZL>** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(PointXYZL*) pointcloud_xyzl_at_colrow(PointCloud<PointXYZL>* ptr, int col, int row)
{
	return &ptr->at(col, row);
}

EXPORT(void) pointcloud_xyzl_add(PointCloud<PointXYZL>* ptr, PointXYZL* value)
{
	//the value needs to be aligned to be pushed into the cloud, so do that.
	PointXYZL deref;
	memcpy(&deref, value, sizeof(PointXYZL));
	ptr->push_back(deref);
}

EXPORT(size_t) pointcloud_xyzl_size(PointCloud<PointXYZL>* ptr)
{
	return ptr->size();
}

EXPORT(void) pointcloud_xyzl_clear(PointCloud<PointXYZL>* ptr)
{
	ptr->clear();
}

EXPORT(uint32_t) pointcloud_xyzl_width(PointCloud<PointXYZL>* ptr)
{
	return ptr->width;
}

EXPORT(void) pointcloud_xyzl_width_set(PointCloud<PointXYZL>* ptr, uint32_t width)
{
	ptr->width = width;
}

EXPORT(uint32_t) pointcloud_xyzl_height(PointCloud<PointXYZL>* ptr)
{
	return ptr->height;
}

EXPORT(void) pointcloud_xyzl_height_set(PointCloud<PointXYZL>* ptr, uint32_t height)
{
	ptr->height = height;
}

EXPORT(int32_t) pointcloud_xyzl_isOrganized(PointCloud<PointXYZL>* ptr)
{
	return ptr->isOrganized();
}

EXPORT(point_vector*) pointcloud_xyzl_points(PointCloud<PointXYZL>* ptr)
{
	return &ptr->points;
}

EXPORT(PointXYZL*) pointcloud_xyzl_data(PointCloud<PointXYZL>* ptr)
{
	return ptr->points.data();
}

EXPORT(void) pointcloud_xyzl_downsample(PointCloud<PointXYZL>* ptr, int factor, PointCloud<PointXYZL>* output)
{
	if (output->width != ptr->width/factor ||
		output->height != ptr->height/factor)
	{
		output->resize(ptr->width/factor * ptr->height/factor);
		output->width = ptr->width/factor;
		output->height = ptr->height/factor;
		output->is_dense = ptr->is_dense;
	}

	if (factor == 1)
	{
		output->points = ptr->points;
		return;
	}

	auto ow = output->width;
	auto oh = output->height;
	auto iw = ptr->width;

	auto oarr = output->points.data();
	auto iarr = ptr->points.data();

	for(size_t c = 0; c < ow; c++)
	{
		for(size_t r = 0; r < oh; r++)
		{
			oarr[r * ow + c] = iarr[r * factor * iw + c * factor];
		}
	}
}

EXPORT(void) pointcloud_xyzl_setIsDense(PointCloud<PointXYZL>* ptr, int value)
{ ptr->is_dense = value; }
EXPORT(int) pointcloud_xyzl_getIsDense(PointCloud<PointXYZL>* ptr)
{ return ptr->is_dense; }

#ifdef __cplusplus  
}
#endif  
